### ISSUE TITLE
Non existant partials error 

### ISSUE THREAD

**Issue by DALDEI** [spullara/mustache.java#137]
In the Specs test there is a test to validate non-existant partials produce "" (and presumably dont error out).  
This works in the JUnit tests but does not work otherwise  - using the default resolver.
The JUnit test explicitly checks if the partial is non existent and if so makes a StringReader("")
The default resolver throw a MustacheException if they cannot resolve the partial.

Which is correct ? Is it intended for users to override the default handling to have spec behavior ?

**Comment by spullara** [comment]
Hmmm. I see. I think when I saw that I was a bit surprised that it doesn't error out as it seems much more likely that the person misspelled the filename than them intending to insert the empty string. In the mustache.js case partials are provided as an object instead of referencing other files. Is the spec behavior useful to you in mustache.java?
