### ISSUE TITLE
Support for array item by index

### ISSUE THREAD

**Issue by vorburger** [spullara/mustache.java#151]
It would be cool if mustache.java would support access of array items by index, as per https://github.com/janl/mustache.js/issues/158

I'm currently working around this, rather uglyly, in an application using mustache, see https://github.com/openMF/mifosx/pull/1448.

If this is already supported (or supported since a more recent version of Mustache than the one we're using in Mifos X perhaps?), please accept my apologies for the wrong bug report - perhaps an update in your README.md could clarify?

**Comment by spullara** [comment]
I don't want to add this to the default implementation as I think it encourages poor separation between the template and the data by bypassing the view, but you can do it:

https://github.com/spullara/mustache.java/blob/master/compiler/src/test/java/com/github/mustachejava/ArraysIndexesTest.java

**Comment by deiga** [comment]
@spullara This seems like a really weird stance as Mustache.js has this functionality. What makes your oppinion better than the original piece you are supposedly implementing?

btw. that example doesn't work when Iterating over the whole array

**Comment by spullara** [comment]
If and when this is added to the spec I will support it by default. In the meantime, if you want to use it, it is relatively easy to include the code I reference above.

**Comment by deiga** [comment]
@spullara This has been in Mustache.js for ages.
And your example breaks iterating over the array.

**Comment by spullara** [comment]
It has been in mustache.js since 2012 (https://github.com/janl/mustache.js/issues/158). Long after mustache.java was created. Most other features go through the specification process which was started in 2010 (https://github.com/mustache/spec) - like template inheritance. I don't know why they decided to add a feature that wasn't spec'd and so I'm not going to add it to the default implementation. I would suggest that you don't use the feature. To me it was a mistake for them to add it.

However, I am happy to help you getting the example working. Why do you think it breaks iterating over the array? That is tested in the test case.

**Comment by deiga** [comment]
Accessing the array throws an `UnsupportedOperationException`

**Comment by spullara** [comment]
Just reproduced the exception, but that was by doing {{test}} .... not sure that is a useful thing to do generally. The normal toString() of an array is opaque. I'm happy to help if you have a particular use case in mind that I am misunderstanding.
