### ISSUE TITLE
Documentation > Improve api documentation

### ISSUE THREAD

**Issue by ghilainm** [spullara/mustache.java#251]
Hi,

Seems like the API documentation is not very descriptive, would it be possible to improve the documentation?

For example, the translate method of the MustacheFactory, I cannot understand what it does. When I look at the code it seems it just returns the value provided as a parameter, what is it supposed to be used for?

Thanks for that :).

**Comment by spullara** [comment]
I agree and I don't remember what circumstances caused me to add it. What it does is let you change a tag name. By default it does nothing. For example, you might have a tag "class" but Java doesn't allow you to use that name because it is a reserved word. So you implement this method and rename class to clazz before variable resolution.
