### ISSUE TITLE
Tag delimiters in partials

### ISSUE THREAD

**Issue by tschut** [spullara/mustache.java#298]
After reading https://github.com/spullara/mustache.java/issues/148 I think there must be a way to configure global default delimiters, such that they are also used in partials. However, I can't find how to do this.

Currently doing:
```
mustacheFactory.compile(mustacheFactory.getReader(templateResource), templateResource, "$$", "$$")
```

Will use the default delimiters in any include partial. Is there a way to change this behaviour?

**Comment by spullara** [comment]
You can extend MustacheParser and override the compile method that uses the default delimiters. Also override createParser in the DefaultMustacheFactory.

**Comment by tschut** [comment]
Works like a charm, thanks for the superfast response!

**Comment by spullara** [comment]
No problem! Generally, I have gone the route of having developers extending classes rather than explicit configuration as the number of things people have asked for over the years is quite staggering and having them all configurable would be a huge mess with likely poor interactions with one another.
